-- ============================================================================
-- Restoration of repository 2026.10 into ontology_authoring
-- ============================================================================
-- GENERATED by ontology_authoring/restore/build_restoration.py.
-- Do not edit by hand; regenerate.
--
-- Source : ontology/source/claris_ontology.sql
-- Digest : sha256 5877bc2971f7d4aa36615753bd55d24d8e232a85a960d1e39a740a83cf5cdc31
--
-- NOT EXECUTED. Awaiting explicit authorization (D.4G.1G.5 section 8).
--
-- Every governance value restored here is UNKNOWN, PROPOSED, OPEN or NULL.
-- Nothing in this file confirms an identity semantic, closes a question,
-- names an authority, or makes any decision executable.
-- ============================================================================

SET search_path = ontology_authoring;

BEGIN;

INSERT INTO ontology_authoring.ontology_release
    (domain, ontology_version, description, status, release_class, validation_status, parent_ontology_version, parent_release_class, source_namespace, source_sha256, content_digest, created_by)
VALUES
    ('retail', '2026.10', 'The Claris retail product model. Eleven object types, seventeen links, twenty-one verbs, twenty evidence types and five decisions. v0.4 separates stable Configuration identity from ConfigurationVersion state from Projection into legacy systems, which is what lets one canonical version and seventy-eight physical rows both be true -- and lets the second be counted as a cost of the source systems rather than as catalogue growth.', 'draft', 'AUTHORITATIVE', NULL, NULL, NULL, 'repository:ontology/source/claris_ontology.sql', 'bf7a2f7f9e1d950f', '5877bc2971f7d4aa36615753bd55d24d8e232a85a960d1e39a740a83cf5cdc31', 'engineering:D.4G.1G.5');

INSERT INTO ontology_authoring.actors
    (domain, ontology_version, actor, ordinal, display_name, actor_kind, members, owns_steps_today, responsibility)
VALUES
    ('retail', '2026.10', 'marketing', 0, 'Marketing', 'department', NULL, 'S1', 'States what Claris intends to sell and into which markets'),
    ('retail', '2026.10', 'ops', 1, 'Ops', 'department', NULL, 'S2, S7, S9, S10, S11, S13, S15, S19', 'Prepares configuration, mints and maintains the legacy representation'),
    ('retail', '2026.10', 'ist', 2, 'IS&T', 'department', NULL, 'S4, S5, S6, S8, S20', 'Owns classification and every projection into a system of record'),
    ('retail', '2026.10', 'finance', 3, 'Finance', 'department', NULL, 'S14, S16, S17', 'Determines and approves commercial price'),
    ('retail', '2026.10', 'ops_ist', 4, 'Ops + IS&T', 'joint_body', 'ops, ist', 'S3', 'Joint hierarchy and classification drafting'),
    ('retail', '2026.10', 'ist_finance', 5, 'IS&T + Finance', 'joint_body', 'ist, finance', 'S12', 'Joint technical readiness approval'),
    ('retail', '2026.10', 'system', 6, 'System', 'machine', NULL, 'S18', 'The overnight ww_pricing to SAP push; the only automated link');

INSERT INTO ontology_authoring.ontology_notes
    (domain, ontology_version, note_id, ordinal, subject, question, blocks, owner, status)
VALUES
    ('retail', '2026.10', 'Q-001', 0, 'slp_code', 'What SLP represents, who owns its definition, and whether it is a configuration dimension, a hierarchy attribute, a pricing dimension or a reference code.', 'identity_rules IR-007; the slp_code dimension', 'UNKNOWN -- naming the owner is the ask', 'OPEN'),
    ('retail', '2026.10', 'Q-002', 1, 'identity_dimensions', 'Which dimensions create a new canonical Configuration rather than a pricing or entitlement variation.', 'IDENTITY_ASSESSMENT; the whole of phase 2', 'Product Management', 'OPEN'),
    ('retail', '2026.10', 'Q-003', 2, 'legacy_update_in_place', 'Whether changing an existing SKU always creates a new all_skus row, or only certain change classes do.', 'projection_rules PR-001, PR-002', 'Ops + IS&T', 'OPEN'),
    ('retail', '2026.10', 'Q-004', 3, 'separation_of_duties', 'The separation-of-duties rules between Ops, IS&T and Finance.', 'action_authorizations', 'IS&T', 'OPEN'),
    ('retail', '2026.10', 'Q-005', 4, 'sellable_definition', 'What Salesforce state constitutes commercially sellable.', 'The READY definition of LAUNCH_READINESS', 'Sales Operations', 'OPEN'),
    ('retail', '2026.10', 'Q-006', 5, 'evidence_capture', 'Which source-system events can be captured automatically in phase 1, and whether the workbench may record approvals.', 'Whether four required evidence types are asserted or permanently absent', 'IS&T', 'OPEN'),
    ('retail', '2026.10', 'Q-007', 6, 'join_key', 'Whether any identifier spans Marketing''s request through to the Salesforce entry, or identity genuinely starts at the material number.', 'Attaching evidence to launches that stall before minting', 'IS&T', 'OPEN');

INSERT INTO ontology_authoring.enums
    (domain, ontology_version, enum_name, ordinal, semantic_definition)
VALUES
    ('retail', '2026.10', 'evidence_state', 0, 'What the platform knows about one fact.'),
    ('retail', '2026.10', 'provenance', 1, 'How strongly it knows it.'),
    ('retail', '2026.10', 'readiness_outcome', 2, 'Conclusions LAUNCH_READINESS may publish.'),
    ('retail', '2026.10', 'identity_effect', 3, 'Conclusions IDENTITY_ASSESSMENT may publish.'),
    ('retail', '2026.10', 'configuration_status', 4, 'Where a governed configuration row stands with Claris.'),
    ('retail', '2026.10', 'use_case_status', 5, 'Whether a catalogued use case can be built today.'),
    ('retail', '2026.10', 'risk', 6, 'Consequence of an action.'),
    ('retail', '2026.10', 'identity_governance', 7, 'Whether a dimension''s identity semantics are settled.'),
    ('retail', '2026.10', 'projection_action', 8, 'What a target system is asked to do for a version.'),
    ('retail', '2026.10', 'projection_reason', 9, 'WHY a target row exists. The column the proliferation measurement is computed from.'),
    ('retail', '2026.10', 'projection_status', 10, 'How far a required projection has got.');

INSERT INTO ontology_authoring.enum_values
    (domain, ontology_version, enum_name, value, ordinal, semantic_definition)
VALUES
    ('retail', '2026.10', 'evidence_state', 'present', 0, 'The fact is established.'),
    ('retail', '2026.10', 'evidence_state', 'absent', 1, 'Nothing asserts it. Forces CANNOT_DECIDE where required.'),
    ('retail', '2026.10', 'evidence_state', 'rejected', 2, 'An owner actively refused, with a reason. Not the same as absent, and the difference is what separates a decision nobody made from one somebody declined to make.'),
    ('retail', '2026.10', 'evidence_state', 'contradicted', 3, 'Two sources disagree. Neither is discarded.'),
    ('retail', '2026.10', 'provenance', 'observed', 0, 'Read from the system that holds the fact.'),
    ('retail', '2026.10', 'provenance', 'inferred', 1, 'Deduced from a downstream artifact.'),
    ('retail', '2026.10', 'provenance', 'asserted', 2, 'A person told the workbench.'),
    ('retail', '2026.10', 'readiness_outcome', 'READY', 0, 'All required evidence present and uncontradicted.'),
    ('retail', '2026.10', 'readiness_outcome', 'BLOCKED', 1, 'Two sources disagree, or an owner explicitly refused. Somebody must reconcile or overturn something.'),
    ('retail', '2026.10', 'readiness_outcome', 'AWAITING_APPROVAL', 2, 'A person owes a judgment and has not given one. Not refused -- untouched. This is where launches sit for 296 days.'),
    ('retail', '2026.10', 'readiness_outcome', 'AWAITING_EVIDENCE', 3, 'A system has not reported a fact yet. Nobody is being asked for anything.'),
    ('retail', '2026.10', 'readiness_outcome', 'CANNOT_DECIDE', 4, 'An upstream decision has not concluded, so the platform cannot even say what is missing.'),
    ('retail', '2026.10', 'identity_effect', 'CREATE_PRODUCT', 0, 'New product family or business concept.'),
    ('retail', '2026.10', 'identity_effect', 'CREATE_CONFIGURATION', 1, 'New sellable identity under an existing product.'),
    ('retail', '2026.10', 'identity_effect', 'USE_EXISTING', 2, 'The requested configuration already exists. The platform returns its identity rather than creating a second one.'),
    ('retail', '2026.10', 'identity_effect', 'NEW_VERSION', 3, 'Existing identity, changed business state. No new configuration; any target row that follows is a projection cost, not catalogue growth.'),
    ('retail', '2026.10', 'identity_effect', 'NO_BUSINESS_CHANGE', 4, 'No canonical mutation.'),
    ('retail', '2026.10', 'identity_effect', 'CANNOT_DECIDE', 5, 'Required evidence or governing policy is missing.'),
    ('retail', '2026.10', 'identity_governance', 'TRUE', 0, 'Confirmed identity-bearing by a named authority.'),
    ('retail', '2026.10', 'identity_governance', 'FALSE', 1, 'Confirmed not identity-bearing by a named authority.'),
    ('retail', '2026.10', 'identity_governance', 'UNKNOWN', 2, 'Nobody has signed. Any change touching this dimension concludes CANNOT_DECIDE / IDENTITY_POLICY_NOT_DEFINED rather than being guessed from a sibling dimension.'),
    ('retail', '2026.10', 'configuration_status', 'proposed', 0, 'We have proposed an answer and shown our reasoning.'),
    ('retail', '2026.10', 'configuration_status', 'confirmed', 1, 'A named person at Claris has signed it.'),
    ('retail', '2026.10', 'configuration_status', 'disputed', 2, 'Claris disagreed; the row needs rework.'),
    ('retail', '2026.10', 'configuration_status', 'undefined', 3, 'No proposal is possible yet.'),
    ('retail', '2026.10', 'use_case_status', 'buildable', 0, 'Nothing external is required. It can be built now.'),
    ('retail', '2026.10', 'use_case_status', 'needs_instances', 1, 'The decision logic exists; the runtime tables that hold concluded decisions do not yet.'),
    ('retail', '2026.10', 'use_case_status', 'blocked', 2, 'Awaiting a named answer from Claris. The blocker is on the row.'),
    ('retail', '2026.10', 'risk', 'low', 0, 'Reversible, no downstream consequence.'),
    ('retail', '2026.10', 'risk', 'elevated', 1, 'Writes to a system of record.'),
    ('retail', '2026.10', 'risk', 'consequential', 2, 'Changes what a customer can buy.'),
    ('retail', '2026.10', 'projection_action', 'CREATE', 0, 'A new physical record in the target system'),
    ('retail', '2026.10', 'projection_action', 'UPDATE', 1, 'An existing target record amended in place'),
    ('retail', '2026.10', 'projection_action', 'RETIRE', 2, 'An existing target record closed or deactivated'),
    ('retail', '2026.10', 'projection_action', 'NO_ACTION', 3, 'The target system needs nothing for this version'),
    ('retail', '2026.10', 'projection_reason', 'BUSINESS_IDENTITY_REQUIRED', 0, 'A genuinely new product or sellable identity'),
    ('retail', '2026.10', 'projection_reason', 'CONFIGURATION_REQUIRED', 1, 'A new governed configuration under an existing product'),
    ('retail', '2026.10', 'projection_reason', 'LEGACY_SYSTEM_CONSTRAINT', 2, 'The canonical model needed no new identity, but the target system cannot version in place'),
    ('retail', '2026.10', 'projection_reason', 'TARGET_SYSTEM_REQUIREMENT', 3, 'The target system''s own model demands a distinct record (SAP material master immutability, for example)'),
    ('retail', '2026.10', 'projection_reason', 'CORRECTION', 4, 'Repairing an earlier bad projection'),
    ('retail', '2026.10', 'projection_reason', 'OTHER', 5, 'Unclassified. Every row here is a gap in the taxonomy.'),
    ('retail', '2026.10', 'projection_status', 'REQUIRED', 0, 'Determined necessary, not yet written'),
    ('retail', '2026.10', 'projection_status', 'PENDING', 1, 'Submitted to the target system'),
    ('retail', '2026.10', 'projection_status', 'CONFIRMED', 2, 'Observed present in the target system'),
    ('retail', '2026.10', 'projection_status', 'FAILED', 3, 'The target system rejected it'),
    ('retail', '2026.10', 'projection_status', 'SUPERSEDED', 4, 'Replaced by a later projection');

INSERT INTO ontology_authoring.configuration_dimensions
    (domain, ontology_version, dimension, ordinal, release_class, governance_basis, label, data_type, identity_affecting, proposed_identity_affecting, governance_state, blocks_identity_assessment, pricing_affecting, entitlement_affecting, hierarchy_affecting, rationale, impact_if_wrong, owner, authority, status, effective_from, effective_to)
VALUES
    ('retail', '2026.10', 'geo', 0, 'AUTHORITATIVE', 'AUTHORITATIVE', 'Region', 'string', 'UNKNOWN', true, 'PROPOSED', true, true, true, NULL, '63 materials in the corpus came from geo additions and none replaced an existing material -- the business already treats a region as a new sellable thing. Each region also carries its own currency and price list.', NULL, 'Product Management', NULL, 'proposed', '2020-01-01', NULL),
    ('retail', '2026.10', 'term', 1, 'AUTHORITATIVE', 'AUTHORITATIVE', 'Term', 'string', 'UNKNOWN', true, 'PROPOSED', true, true, true, NULL, '33 materials, none replacing an existing one. Annual and monthly are different commitments with different revenue recognition, not two prices for the same thing.', NULL, 'Product Management', NULL, 'proposed', '2020-01-01', NULL),
    ('retail', '2026.10', 'segment', 2, 'AUTHORITATIVE', 'AUTHORITATIVE', 'Segment', 'string', 'UNKNOWN', true, 'PROPOSED', true, true, true, NULL, '19 materials, none replacing an existing one. Retail, education and partner carry different entitlement and eligibility, not only a different price.', NULL, 'Product Management + Finance', NULL, 'proposed', '2020-01-01', NULL),
    ('retail', '2026.10', 'user_tier', 3, 'AUTHORITATIVE', 'AUTHORITATIVE', 'User tier', 'range_band', 'UNKNOWN', false, 'PROPOSED', true, true, true, false, 'THE EXPENSIVE ONE. 78 of the 92 materials that replaced an existing material came from tier restructures. A tier band changes what a customer pays, not what they buy -- which makes it a price break, not an identity. If Claris agrees, those 78 materials never needed to be minted, hierarchied, approved, priced and published.', '78 materials per restructure cycle', 'Product Management', NULL, 'proposed', '2020-01-01', NULL),
    ('retail', '2026.10', 'package_format', 4, 'AUTHORITATIVE', 'AUTHORITATIVE', 'Package format', 'string', 'UNKNOWN', true, 'PROPOSED', true, true, true, true, '12 materials from repackaging, all replacing an existing one. Perpetual and subscription are different fulfilment and different contracts, so this proliferation looks legitimate.', NULL, 'Product Management', NULL, 'proposed', '2020-01-01', NULL),
    ('retail', '2026.10', 'currency', 5, 'AUTHORITATIVE', 'AUTHORITATIVE', 'Currency', 'string', 'UNKNOWN', false, 'PROPOSED', true, true, false, false, 'Currency is derived from region, never chosen independently. Making it identity-bearing would multiply every region by its currency for no business gain.', NULL, 'Finance', NULL, 'proposed', '2020-01-01', NULL),
    ('retail', '2026.10', 'slp_code', 6, 'AUTHORITATIVE', 'AUTHORITATIVE', 'SLP', 'string', 'UNKNOWN', NULL, 'UNPROPOSED', true, NULL, NULL, NULL, 'NO PROPOSAL POSSIBLE. No definition of SLP exists anywhere in the process documentation. It is assigned at S3 beside the hierarchy path, eleven steps before pricing, which suggests a classification code rather than a price -- but that is an inference from position, not knowledge.', NULL, 'UNKNOWN -- identifying the owner is itself the ask', NULL, 'undefined', '2020-01-01', NULL),
    ('retail', '2026.10', 'description', 7, 'AUTHORITATIVE', 'AUTHORITATIVE', 'Description', 'string', 'UNKNOWN', false, 'PROPOSED', true, false, false, false, 'Metadata. Correcting a typo must never mint a SKU.', NULL, 'Marketing', NULL, 'proposed', '2020-01-01', NULL);

INSERT INTO ontology_authoring.identity_rules
    (domain, ontology_version, rule, ordinal, release_class, governance_basis, change_type, reads_dimension, condition_expression, proposed_effect, identity_effect, governance_state, observed_materials, rationale, owner, authority, status)
VALUES
    ('retail', '2026.10', 'IR-001', 0, 'AUTHORITATIVE', 'AUTHORITATIVE', 'new_product_family', NULL, 'always', 'CREATE_PRODUCT', NULL, 'PROPOSED', 9, 'A new family is a new commercial product by definition.', 'Product Management', NULL, 'proposed'),
    ('retail', '2026.10', 'IR-002', 1, 'AUTHORITATIVE', 'AUTHORITATIVE', 'geo_add', 'geo', 'geo.identity_affecting', 'CREATE_CONFIGURATION', NULL, 'PROPOSED', 63, 'Legitimate catalogue growth; none of the 63 replaced anything.', 'Product Management', NULL, 'proposed'),
    ('retail', '2026.10', 'IR-003', 2, 'AUTHORITATIVE', 'AUTHORITATIVE', 'term_add', 'term', 'term.identity_affecting', 'CREATE_CONFIGURATION', NULL, 'PROPOSED', 33, 'Different commitment, different contract.', 'Product Management', NULL, 'proposed'),
    ('retail', '2026.10', 'IR-004', 3, 'AUTHORITATIVE', 'AUTHORITATIVE', 'segment_add', 'segment', 'segment.identity_affecting', 'CREATE_CONFIGURATION', NULL, 'PROPOSED', 19, 'Entitlement differs, not only price.', 'Product Management + Finance', NULL, 'proposed'),
    ('retail', '2026.10', 'IR-005', 4, 'AUTHORITATIVE', 'AUTHORITATIVE', 'tier_restructure', 'user_tier', 'user_tier.identity_affecting', 'NEW_VERSION', NULL, 'PROPOSED', 78, 'THE DECISION WORTH MONEY. Proposed as an update, which would have avoided 78 of the 92 mutative materials in the corpus. If Claris says user tier IS identity-bearing, this becomes CREATE_CONFIGURATION and the proliferation is unavoidable.', 'Product Management', NULL, 'proposed'),
    ('retail', '2026.10', 'IR-006', 5, 'AUTHORITATIVE', 'AUTHORITATIVE', 'repackage', 'package_format', 'package_format.identity_affecting', 'CREATE_CONFIGURATION', NULL, 'PROPOSED', 12, 'Different fulfilment; the 12 replacements look legitimate.', 'Product Management', NULL, 'proposed'),
    ('retail', '2026.10', 'IR-007', 6, 'AUTHORITATIVE', 'AUTHORITATIVE', 'reclassify', 'slp_code', 'hierarchy_path changed', 'NEW_VERSION', NULL, 'PROPOSED', 2, 'Reclassification changes where a product sits, not what it is. Today it mints; proposed as an amendment.', 'IS&T', NULL, 'proposed'),
    ('retail', '2026.10', 'IR-008', 7, 'AUTHORITATIVE', 'AUTHORITATIVE', 'price_change', NULL, 'always', 'NEW_VERSION', NULL, 'PROPOSED', 0, 'Confirmed by the corpus: three price changes minted nothing.', 'Finance', NULL, 'proposed'),
    ('retail', '2026.10', 'IR-009', 8, 'AUTHORITATIVE', 'AUTHORITATIVE', 'rename', 'description', 'always', 'NO_BUSINESS_CHANGE', NULL, 'PROPOSED', 0, 'Confirmed by the corpus: two renames minted nothing.', 'Marketing', NULL, 'proposed');

INSERT INTO ontology_authoring.decisions
    (domain, ontology_version, decision, ordinal, subject_type, question, mode, accountable_actor, authority, status, phase, replaces_today, blocked_on, blocked_by_note)
VALUES
    ('retail', '2026.10', 'LAUNCH_READINESS', 0, 'configuration_version', 'Can this version be activated and sold?', 'recommend', 'ops', NULL, 'proposed', 1, 'S5, S7, S12, S16, S17', NULL, NULL),
    ('retail', '2026.10', 'COMMERCIAL_INTENT', 1, 'launch', 'Should Claris sell this, into these markets, by this date?', 'human_approval', 'marketing', NULL, 'proposed', 1, 'S1', NULL, NULL),
    ('retail', '2026.10', 'LAUNCH_VIABILITY', 2, 'launch', 'Is this launch still worth finishing?', 'human_approval', 'marketing', NULL, 'proposed', 1, NULL, NULL, NULL),
    ('retail', '2026.10', 'CHANGE_CLASSIFICATION', 3, 'launch', 'What kind of change is being requested?', 'recommend', 'ops', NULL, 'proposed', 1, 'S1, S2', NULL, NULL),
    ('retail', '2026.10', 'IDENTITY_ASSESSMENT', 4, 'launch', 'Does this change require a new canonical identity, a new version of an existing one, or nothing at all?', 'recommend', 'ops', NULL, 'proposed', 1, NULL, 'Claris confirmation of which dimensions are identity-affecting', 'Q-002');

INSERT INTO ontology_authoring.decision_outputs
    (domain, ontology_version, decision, outcome, ordinal, release_class, governance_basis, semantic_definition, entitles_actions, governance_state)
VALUES
    ('retail', '2026.10', 'LAUNCH_READINESS', 'READY', 0, 'AUTHORITATIVE', 'AUTHORITATIVE', 'All required evidence present and uncontradicted', 'ACTIVATE_MATERIAL, PUBLISH_TO_SALESFORCE', 'PROPOSED'),
    ('retail', '2026.10', 'LAUNCH_READINESS', 'BLOCKED', 1, 'AUTHORITATIVE', 'AUTHORITATIVE', 'Two sources disagree, or an owner has explicitly refused. Somebody must reconcile or overturn something before this moves.', NULL, 'PROPOSED'),
    ('retail', '2026.10', 'LAUNCH_READINESS', 'AWAITING_APPROVAL', 2, 'AUTHORITATIVE', 'AUTHORITATIVE', 'A person owes a judgment and has not given one. Not refused -- untouched. This is where launches sit for 296 days.', NULL, 'PROPOSED'),
    ('retail', '2026.10', 'LAUNCH_READINESS', 'AWAITING_EVIDENCE', 3, 'AUTHORITATIVE', 'AUTHORITATIVE', 'A system has not yet reported a fact the platform expects. Nobody is being asked for anything; something has not propagated.', NULL, 'PROPOSED'),
    ('retail', '2026.10', 'LAUNCH_READINESS', 'CANNOT_DECIDE', 4, 'AUTHORITATIVE', 'AUTHORITATIVE', 'The platform cannot even determine what is missing, because an upstream decision has not concluded.', NULL, 'PROPOSED'),
    ('retail', '2026.10', 'COMMERCIAL_INTENT', 'APPROVED', 0, 'AUTHORITATIVE', 'AUTHORITATIVE', 'Claris intends to sell this', 'SUBMIT_INTENT', 'PROPOSED'),
    ('retail', '2026.10', 'COMMERCIAL_INTENT', 'DEFERRED', 1, 'AUTHORITATIVE', 'AUTHORITATIVE', 'Wanted, but not now. The launch does not start.', NULL, 'PROPOSED'),
    ('retail', '2026.10', 'COMMERCIAL_INTENT', 'REJECTED', 2, 'AUTHORITATIVE', 'AUTHORITATIVE', 'Not wanted', NULL, 'PROPOSED'),
    ('retail', '2026.10', 'LAUNCH_VIABILITY', 'CONTINUE', 0, 'AUTHORITATIVE', 'AUTHORITATIVE', 'Still wanted; the blockage is worth clearing', NULL, 'PROPOSED'),
    ('retail', '2026.10', 'LAUNCH_VIABILITY', 'ABANDON', 1, 'AUTHORITATIVE', 'AUTHORITATIVE', 'No longer worth finishing. Stops the launch and releases what it holds.', 'ABANDON_LAUNCH', 'PROPOSED'),
    ('retail', '2026.10', 'LAUNCH_VIABILITY', 'NOT_ASKED', 2, 'AUTHORITATIVE', 'AUTHORITATIVE', 'Nobody has been asked. The default, and the state every stalled launch in the corpus is in.', NULL, 'PROPOSED'),
    ('retail', '2026.10', 'CHANGE_CLASSIFICATION', 'offering_launch', 0, 'AUTHORITATIVE', 'AUTHORITATIVE', 'A product family Claris does not sell today', NULL, 'PROPOSED'),
    ('retail', '2026.10', 'CHANGE_CLASSIFICATION', 'geo_add', 1, 'AUTHORITATIVE', 'AUTHORITATIVE', 'An existing offering into a new market', NULL, 'PROPOSED'),
    ('retail', '2026.10', 'CHANGE_CLASSIFICATION', 'term_add', 2, 'AUTHORITATIVE', 'AUTHORITATIVE', 'A new commitment length on an existing offering', NULL, 'PROPOSED'),
    ('retail', '2026.10', 'CHANGE_CLASSIFICATION', 'segment_add', 3, 'AUTHORITATIVE', 'AUTHORITATIVE', 'A new customer segment on an existing offering', NULL, 'PROPOSED'),
    ('retail', '2026.10', 'CHANGE_CLASSIFICATION', 'tier_restructure', 4, 'AUTHORITATIVE', 'AUTHORITATIVE', 'The user-tier bands change', NULL, 'PROPOSED'),
    ('retail', '2026.10', 'CHANGE_CLASSIFICATION', 'repackage', 5, 'AUTHORITATIVE', 'AUTHORITATIVE', 'The fulfilment or packaging form changes', NULL, 'PROPOSED'),
    ('retail', '2026.10', 'CHANGE_CLASSIFICATION', 'reclassify', 6, 'AUTHORITATIVE', 'AUTHORITATIVE', 'The hierarchy position changes; nothing sellable changes', NULL, 'PROPOSED'),
    ('retail', '2026.10', 'CHANGE_CLASSIFICATION', 'price_change', 7, 'AUTHORITATIVE', 'AUTHORITATIVE', 'Price only', NULL, 'PROPOSED'),
    ('retail', '2026.10', 'CHANGE_CLASSIFICATION', 'rename', 8, 'AUTHORITATIVE', 'AUTHORITATIVE', 'Descriptive metadata only', NULL, 'PROPOSED'),
    ('retail', '2026.10', 'CHANGE_CLASSIFICATION', 'CANNOT_DECIDE', 9, 'AUTHORITATIVE', 'AUTHORITATIVE', 'The request does not say enough to classify', NULL, 'PROPOSED'),
    ('retail', '2026.10', 'IDENTITY_ASSESSMENT', 'CREATE_PRODUCT', 0, 'AUTHORITATIVE', 'AUTHORITATIVE', 'New product family or business concept', 'CREATE_PRODUCT', 'PROPOSED'),
    ('retail', '2026.10', 'IDENTITY_ASSESSMENT', 'CREATE_CONFIGURATION', 1, 'AUTHORITATIVE', 'AUTHORITATIVE', 'New sellable identity under an existing product', 'CREATE_CONFIGURATION', 'PROPOSED'),
    ('retail', '2026.10', 'IDENTITY_ASSESSMENT', 'USE_EXISTING', 2, 'AUTHORITATIVE', 'AUTHORITATIVE', 'The requested sellable configuration already exists. The platform returns its identity instead of creating a second one.', NULL, 'PROPOSED'),
    ('retail', '2026.10', 'IDENTITY_ASSESSMENT', 'NEW_VERSION', 3, 'AUTHORITATIVE', 'AUTHORITATIVE', 'Existing identity, changed business state. No new configuration. Any target-system row that follows is a projection cost, not catalogue growth.', 'CREATE_VERSION', 'PROPOSED'),
    ('retail', '2026.10', 'IDENTITY_ASSESSMENT', 'NO_BUSINESS_CHANGE', 4, 'AUTHORITATIVE', 'AUTHORITATIVE', 'No canonical mutation. Nothing in the request changes what Claris sells or how it is represented.', NULL, 'PROPOSED'),
    ('retail', '2026.10', 'IDENTITY_ASSESSMENT', 'CANNOT_DECIDE', 5, 'AUTHORITATIVE', 'AUTHORITATIVE', 'Required evidence or governing policy is missing. The platform names the gap rather than defaulting.', NULL, 'PROPOSED');

INSERT INTO ontology_authoring.decision_reason_codes
    (domain, ontology_version, reason_code, ordinal, scope, decision_type, semantic_definition, governance_state)
VALUES
    ('retail', '2026.10', 'IDENTITY_POLICY_NOT_DEFINED', 0, 'DECISION_SPECIFIC', 'IDENTITY_ASSESSMENT', 'No confirmed identity rule exists for a dimension this change touches. The platform declines rather than guessing.', 'PROPOSED'),
    ('retail', '2026.10', 'EVIDENCE_ABSENT', 1, 'PLATFORM', NULL, 'A required statement has never been made by anyone', 'PROPOSED'),
    ('retail', '2026.10', 'EVIDENCE_CONTRADICTED', 2, 'PLATFORM', NULL, 'Two sources disagree and neither has been reconciled', 'PROPOSED'),
    ('retail', '2026.10', 'EVIDENCE_REJECTED', 3, 'PLATFORM', NULL, 'An owner explicitly refused, with a reason', 'PROPOSED'),
    ('retail', '2026.10', 'DEPENDENCY_UNRESOLVED', 4, 'PLATFORM', NULL, 'An upstream decision has not concluded', 'PROPOSED'),
    ('retail', '2026.10', 'REQUEST_UNDERSPECIFIED', 5, 'PLATFORM', NULL, 'The change request does not say enough to classify', 'PROPOSED');

INSERT INTO ontology_authoring.decision_dependencies
    (domain, ontology_version, decision, depends_on, ordinal, required_outcome, dependency_type, upstream_actor, upstream_phase)
VALUES
    ('retail', '2026.10', 'LAUNCH_READINESS', 'CHANGE_CLASSIFICATION', 0, NULL, 'HARD_GATE', 'Ops', 1),
    ('retail', '2026.10', 'LAUNCH_VIABILITY', 'COMMERCIAL_INTENT', 0, NULL, 'HARD_GATE', 'Marketing', 1),
    ('retail', '2026.10', 'CHANGE_CLASSIFICATION', 'COMMERCIAL_INTENT', 0, NULL, 'HARD_GATE', 'Marketing', 1),
    ('retail', '2026.10', 'IDENTITY_ASSESSMENT', 'CHANGE_CLASSIFICATION', 0, NULL, 'HARD_GATE', 'Ops', 1);

INSERT INTO ontology_authoring.projection_rules
    (domain, ontology_version, rule, ordinal, source_object, target_system, proposed_action, projection_reason, requires_new_target_identity, rationale, owner, authority, status)
VALUES
    ('retail', '2026.10', 'PR-001', 0, 'configuration', 'all_skus', 'CREATE', NULL, true, 'Today every change mints a new row. Which change classes may update in place is the question that decides whether an UPDATE_EXISTING conclusion actually avoids a legacy row.', 'Ops', NULL, 'confirm_with_claris'),
    ('retail', '2026.10', 'PR-002', 1, 'configuration', 'sap', 'CREATE', NULL, true, 'Material master identity is assumed immutable; confirm.', 'IS&T', NULL, 'confirm_with_claris'),
    ('retail', '2026.10', 'PR-003', 2, 'price', 'ww_pricing', 'UPDATE', NULL, false, 'Price rows are versioned in place today.', 'Finance', NULL, 'proposed'),
    ('retail', '2026.10', 'PR-004', 3, 'configuration', 'salesforce', 'CREATE', NULL, false, 'Pricebook entries follow the material.', 'IS&T', NULL, 'proposed');

-- evidence_reference: 0 rows. No governance evidence exists yet.

COMMIT;
