-- ============================================================================
-- PROTOTYPE GOVERNANCE RELEASE  2026.10-prototype.1
-- ============================================================================
--            *** PROTOTYPE -- NOT CLARIS APPROVED ***
--            *** FOR DEMONSTRATION ONLY ***
--            *** TO BE VALIDATED WITH CLARIS ***
--
-- GENERATED by ontology_authoring/restore/build_prototype.py. Do not edit.
-- Parent authoritative release: 2026.10
-- Source digest: sha256 5877bc2971f7d4aa36615753bd55d24d8e232a85a960d1e39a740a83cf5cdc31
--
-- NOT EXECUTED. Awaiting explicit authorization.
--
-- Every governed value here is an engineering assumption. Nothing in this
-- file is confirmed governance: no row carries an authority, a confirmed_by
-- or a confirmed_on, identity_affecting is UNKNOWN throughout, and
-- identity_effect is NULL throughout. Q-001 through Q-007 remain open in the
-- authoritative release and this release does not close any of them.
--
-- IR-007 (reclassify / SLP) is deliberately ABSENT. See
-- prototype_assumptions.md.
-- ============================================================================

SET search_path = ontology_authoring;

BEGIN;

INSERT INTO ontology_authoring.ontology_release
    (domain, ontology_version, description, status, release_class, validation_status, parent_ontology_version, parent_release_class, source_namespace, source_sha256, content_digest, created_by)
VALUES
    ('retail', '2026.10-prototype.1', 'PROTOTYPE. NOT CLARIS APPROVED. FOR DEMONSTRATION ONLY. Every governed value in this release is an engineering assumption awaiting validation with Claris. Q-001 through Q-007 remain open.', 'draft', 'PROTOTYPE', 'TO_BE_VALIDATED_WITH_CLARIS', '2026.10', 'AUTHORITATIVE', 'repository:ontology/source/claris_ontology.sql', NULL, '5877bc2971f7d4aa36615753bd55d24d8e232a85a960d1e39a740a83cf5cdc31', 'engineering:D.4G.1G.5P.1');

INSERT INTO ontology_authoring.actors
    (domain, ontology_version, actor, ordinal, display_name, actor_kind, members, owns_steps_today, responsibility)
VALUES
    ('retail', '2026.10-prototype.1', 'marketing', 0, 'Marketing', 'department', NULL, 'S1', 'States what Claris intends to sell and into which markets'),
    ('retail', '2026.10-prototype.1', 'ops', 1, 'Ops', 'department', NULL, 'S2, S7, S9, S10, S11, S13, S15, S19', 'Prepares configuration, mints and maintains the legacy representation'),
    ('retail', '2026.10-prototype.1', 'ist', 2, 'IS&T', 'department', NULL, 'S4, S5, S6, S8, S20', 'Owns classification and every projection into a system of record'),
    ('retail', '2026.10-prototype.1', 'finance', 3, 'Finance', 'department', NULL, 'S14, S16, S17', 'Determines and approves commercial price'),
    ('retail', '2026.10-prototype.1', 'ops_ist', 4, 'Ops + IS&T', 'joint_body', 'ops, ist', 'S3', 'Joint hierarchy and classification drafting'),
    ('retail', '2026.10-prototype.1', 'ist_finance', 5, 'IS&T + Finance', 'joint_body', 'ist, finance', 'S12', 'Joint technical readiness approval'),
    ('retail', '2026.10-prototype.1', 'system', 6, 'System', 'machine', NULL, 'S18', 'The overnight ww_pricing to SAP push; the only automated link');

INSERT INTO ontology_authoring.decisions
    (domain, ontology_version, decision, ordinal, subject_type, question, mode, accountable_actor, authority, status, phase, blocked_on, blocked_by_note)
VALUES
    ('retail', '2026.10-prototype.1', 'IDENTITY_ASSESSMENT', 0, 'launch', 'Does this change require a new canonical identity, a new version of an existing one, or nothing at all?', 'recommend', 'ops', NULL, 'proposed', 1, 'PROTOTYPE RELEASE. Q-002 remains open in the authoritative release; this release executes an engineering assumption instead of a Claris confirmation.', NULL);

INSERT INTO ontology_authoring.decision_outputs
    (domain, ontology_version, decision, outcome, ordinal, release_class, governance_basis, semantic_definition, governance_state)
VALUES
    ('retail', '2026.10-prototype.1', 'IDENTITY_ASSESSMENT', 'CREATE_PRODUCT', 0, 'PROTOTYPE', 'PROTOTYPE_ASSUMPTION', 'New product family or business concept.', 'PROPOSED'),
    ('retail', '2026.10-prototype.1', 'IDENTITY_ASSESSMENT', 'CREATE_CONFIGURATION', 1, 'PROTOTYPE', 'PROTOTYPE_ASSUMPTION', 'New sellable identity under an existing product.', 'PROPOSED'),
    ('retail', '2026.10-prototype.1', 'IDENTITY_ASSESSMENT', 'USE_EXISTING', 2, 'PROTOTYPE', 'PROTOTYPE_ASSUMPTION', 'The requested sellable configuration already exists; its identity is returned rather than a second one created.', 'PROPOSED'),
    ('retail', '2026.10-prototype.1', 'IDENTITY_ASSESSMENT', 'NEW_VERSION', 3, 'PROTOTYPE', 'PROTOTYPE_ASSUMPTION', 'Existing identity, changed business state. No new configuration.', 'PROPOSED'),
    ('retail', '2026.10-prototype.1', 'IDENTITY_ASSESSMENT', 'NO_BUSINESS_CHANGE', 4, 'PROTOTYPE', 'PROTOTYPE_ASSUMPTION', 'No canonical mutation.', 'PROPOSED'),
    ('retail', '2026.10-prototype.1', 'IDENTITY_ASSESSMENT', 'CANNOT_DECIDE', 5, 'PROTOTYPE', 'PROTOTYPE_ASSUMPTION', 'Required evidence or governing policy is missing. The platform names the gap rather than defaulting.', 'PROPOSED');

INSERT INTO ontology_authoring.configuration_dimensions
    (domain, ontology_version, dimension, ordinal, release_class, governance_basis, label, data_type, identity_affecting, proposed_identity_affecting, governance_state, blocks_identity_assessment, rationale, owner, authority, status)
VALUES
    ('retail', '2026.10-prototype.1', 'product_reference', 0, 'PROTOTYPE', 'PROTOTYPE_ASSUMPTION', 'Product reference', 'string', 'UNKNOWN', true, 'PROPOSED', true, 'PROTOTYPE ASSUMPTION. Prototype-only: 2026.10 has no counterpart. Q-007 asks whether any identifier spans the process, or identity starts at the material number.', NULL, NULL, 'proposed'),
    ('retail', '2026.10-prototype.1', 'geography', 1, 'PROTOTYPE', 'PROTOTYPE_ASSUMPTION', 'Geography', 'string', 'UNKNOWN', true, 'PROPOSED', true, 'PROTOTYPE ASSUMPTION. The prototype''s name for the 2026.10 ''geo'' dimension, which is UNKNOWN and unsigned there. 63 materials from geo additions, none replacing an existing material.', NULL, NULL, 'proposed'),
    ('retail', '2026.10-prototype.1', 'term_months', 2, 'PROTOTYPE', 'PROTOTYPE_ASSUMPTION', 'Contract term (months)', 'string', 'UNKNOWN', true, 'PROPOSED', true, 'PROTOTYPE ASSUMPTION. The prototype''s name for the 2026.10 ''term'' dimension, which is UNKNOWN and unsigned there. Q-009 asks whether term months and contract length months are the same business concept.', NULL, NULL, 'proposed'),
    ('retail', '2026.10-prototype.1', 'customer_segment', 3, 'PROTOTYPE', 'PROTOTYPE_ASSUMPTION', 'Customer segment', 'string', 'UNKNOWN', true, 'PROPOSED', true, 'PROTOTYPE ASSUMPTION. The prototype''s name for the 2026.10 ''segment'' dimension, which is UNKNOWN and unsigned there.', NULL, NULL, 'proposed'),
    ('retail', '2026.10-prototype.1', 'user_tier', 4, 'PROTOTYPE', 'PROTOTYPE_ASSUMPTION', 'User tier', 'string', 'UNKNOWN', false, 'PROPOSED', true, 'PROTOTYPE ASSUMPTION -- THE MOST CONSEQUENTIAL ONE IN THIS RELEASE. Assumed NOT identity-bearing, which is what makes IR-005 conclude NEW_VERSION and what avoids 78 of the 92 replacement materials in the corpus. If Claris says user tier IS identity-bearing, IR-005 becomes CREATE_CONFIGURATION and that saving does not exist. Unvalidated.', NULL, NULL, 'proposed'),
    ('retail', '2026.10-prototype.1', 'package_format', 5, 'PROTOTYPE', 'PROTOTYPE_ASSUMPTION', 'Package format', 'string', 'UNKNOWN', false, 'PROPOSED', true, 'PROTOTYPE ASSUMPTION WITH A RECORDED CONFLICT. 2026.10 proposes this dimension IS identity-bearing (IR-006 -> CREATE_CONFIGURATION), but the locked prototype identity tuple excludes it, so this release assumes NOT identity-bearing in order to keep the tuple at four properties. The two assumptions disagree: under this release a repackage yields an identical canonical identity and the exact-match predicate concludes NO_BUSINESS_CHANGE, so the CREATE_CONFIGURATION that IR-006 proposes is unreachable. Recorded, not resolved: resolving it means changing tuple membership, which G.5P locked.', NULL, NULL, 'proposed'),
    ('retail', '2026.10-prototype.1', 'description', 6, 'PROTOTYPE', 'PROTOTYPE_ASSUMPTION', 'Description', 'string', 'UNKNOWN', false, 'PROPOSED', true, 'PROTOTYPE ASSUMPTION. Assumed not identity-bearing, matching 2026.10''s own proposal. 2026.10 marks it CONFIRMED but with no confirmed_by or confirmed_on, so it is unsigned there and unconfirmed here.', NULL, NULL, 'proposed');

INSERT INTO ontology_authoring.identity_rules
    (domain, ontology_version, rule, ordinal, release_class, governance_basis, change_type, reads_dimension, proposed_effect, identity_effect, governance_state, rationale, blocking_note, owner, authority, status)
VALUES
    ('retail', '2026.10-prototype.1', 'IR-001', 0, 'PROTOTYPE', 'PROTOTYPE_ASSUMPTION', 'new_product_family', NULL, 'CREATE_PRODUCT', NULL, 'PROPOSED', 'Tautological in the source: a new family is a new commercial product by definition. Reads no dimension.', NULL, NULL, NULL, 'proposed'),
    ('retail', '2026.10-prototype.1', 'IR-002', 1, 'PROTOTYPE', 'PROTOTYPE_ASSUMPTION', 'geo_add', 'geography', 'CREATE_CONFIGURATION', NULL, 'PROPOSED', '63 materials in the corpus came from geo additions and none replaced an existing material.', NULL, NULL, NULL, 'proposed'),
    ('retail', '2026.10-prototype.1', 'IR-003', 2, 'PROTOTYPE', 'PROTOTYPE_ASSUMPTION', 'term_add', 'term_months', 'CREATE_CONFIGURATION', NULL, 'PROPOSED', '33 materials, none replacing an existing one.', NULL, NULL, NULL, 'proposed'),
    ('retail', '2026.10-prototype.1', 'IR-004', 3, 'PROTOTYPE', 'PROTOTYPE_ASSUMPTION', 'segment_add', 'customer_segment', 'CREATE_CONFIGURATION', NULL, 'PROPOSED', '19 materials, none replacing an existing one.', NULL, NULL, NULL, 'proposed'),
    ('retail', '2026.10-prototype.1', 'IR-005', 4, 'PROTOTYPE', 'PROTOTYPE_ASSUMPTION', 'tier_restructure', 'user_tier', 'NEW_VERSION', NULL, 'PROPOSED', '78 of the 92 materials that replaced an existing material came from tier restructures. This assumption is what turns them into versions.', 'PROMINENT LABEL REQUIRED. This is the single most consequential assumption in the release and the one most expensive to get wrong. Any figure derived from it must be shown alongside the fact that it is unvalidated.', NULL, NULL, 'proposed'),
    ('retail', '2026.10-prototype.1', 'IR-006', 5, 'PROTOTYPE', 'PROTOTYPE_ASSUMPTION', 'repackage', 'package_format', NULL, NULL, 'UNPROPOSED', '12 materials from repackaging, all replacing an existing one.', 'NOT EXECUTABLE IN THIS PROTOTYPE (D.4G.2 section 1). 2026.10 proposes repackage -> CREATE_CONFIGURATION, but package_format is not one of the four locked identity properties, so the two assumptions cannot both execute coherently. The rule is retained for provenance with proposed_effect NULL and status undefined, so no executable derivation can reach it. A repackage must conclude CANNOT_DECIDE / IDENTITY_POLICY_NOT_DEFINED, exactly as reclassify/SLP does. Resolving it means changing tuple membership, which G.5P locked.', NULL, NULL, 'undefined'),
    ('retail', '2026.10-prototype.1', 'IR-008', 6, 'PROTOTYPE', 'PROTOTYPE_ASSUMPTION', 'price_change', NULL, 'NEW_VERSION', NULL, 'PROPOSED', 'Verified against the corpus: three price changes minted nothing. Reads no dimension.', NULL, NULL, NULL, 'proposed'),
    ('retail', '2026.10-prototype.1', 'IR-009', 7, 'PROTOTYPE', 'PROTOTYPE_ASSUMPTION', 'rename', 'description', 'NO_BUSINESS_CHANGE', NULL, 'PROPOSED', 'Verified against the corpus: two renames minted nothing.', NULL, NULL, NULL, 'proposed');

INSERT INTO ontology_authoring.decision_rule_bindings
    (domain, ontology_version, release_class, governance_basis, decision, rule_id, predicate_name, rule_class, precedence, expected_outcome, description, status)
VALUES
    ('retail', '2026.10-prototype.1', 'PROTOTYPE', 'PROTOTYPE_ASSUMPTION', 'IDENTITY_ASSESSMENT', 'IA-PRED-001', 'ir_011_missing_required_input', 'GUARD', 1, 'CANNOT_DECIDE', 'Missing required identity input.', 'proposed'),
    ('retail', '2026.10-prototype.1', 'PROTOTYPE', 'PROTOTYPE_ASSUMPTION', 'IDENTITY_ASSESSMENT', 'IA-PRED-002', 'ir_012_contradicted_required_input', 'GUARD', 2, 'CANNOT_DECIDE', 'Contradicted required identity input.', 'proposed'),
    ('retail', '2026.10-prototype.1', 'PROTOTYPE', 'PROTOTYPE_ASSUMPTION', 'IDENTITY_ASSESSMENT', 'IA-PRED-003', 'ir_013_initial_configuration', 'MATCH', 5, 'CREATE_CONFIGURATION', 'No configuration exists for this product yet.', 'proposed'),
    ('retail', '2026.10-prototype.1', 'PROTOTYPE', 'PROTOTYPE_ASSUMPTION', 'IDENTITY_ASSESSMENT', 'IA-PRED-004', 'ir_010_exact_identity_match', 'MATCH', 6, 'NO_BUSINESS_CHANGE', 'An active configuration already carries this canonical identity.', 'proposed');

COMMIT;
