"""Communication drafting, as business evidence rather than as a mail client.

WHAT THIS DOES AND DOES NOT DO
-------------------------------
It drafts. It does not send. There is no SMTP, no Gmail, no external messaging
integration anywhere in this module, and a draft is never described as having
been sent -- `status` is DRAFT and the only channels are WORKBENCH_NOTE and
EMAIL_DRAFT.

The point of recording a draft at all is that coordination is business
evidence. "Finance was asked for a pricing decision on the 3rd and has not
answered" is a fact about the launch, and a Workbench that cannot show it
cannot explain why a launch stalled. So a communication is a row with a
recipient, a reason, a moment and a link to the decision it concerns -- not a
message in someone's outbox.

NO FABRICATED RECIPIENTS
------------------------
If a person's identity is not established, `to_actor` is None and `to_role`
carries the role. Every actor id in this corpus is a simulation marker, so in
practice every draft here addresses a role. Inventing a name and an address to
make a demo read better would put a fictional person into a business record --
and the record is meant to be the honest part.

The recipient role itself comes from the coordination analysis, which derives
it from governed metadata or reports that it is not established. A draft whose
recipient could not be determined says so in its own body rather than going to
a plausible-sounding team.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass
from typing import Any, Mapping, Optional

__all__ = [
    "CHANNELS",
    "COMMUNICATION_TYPES",
    "STATUS_DRAFT",
    "CommunicationDraft",
    "draft_for",
]

CHANNEL_NOTE = "WORKBENCH_NOTE"
CHANNEL_EMAIL_DRAFT = "EMAIL_DRAFT"
CHANNELS = (CHANNEL_NOTE, CHANNEL_EMAIL_DRAFT)

TYPE_REQUEST_EVIDENCE = "REQUEST_EVIDENCE"
TYPE_REQUEST_DECISION = "REQUEST_DECISION"
TYPE_ESTABLISH_OWNER = "ESTABLISH_DECISION_OWNER"
TYPE_RESOLVE_AMBIGUITY = "RESOLVE_GOVERNANCE_AMBIGUITY"
TYPE_NOTE = "NOTE"
COMMUNICATION_TYPES = (TYPE_REQUEST_EVIDENCE, TYPE_REQUEST_DECISION,
                       TYPE_ESTABLISH_OWNER, TYPE_RESOLVE_AMBIGUITY, TYPE_NOTE)

#: The only status a drafted communication may carry. There is no SENT here,
#: because nothing in this module can send.
STATUS_DRAFT = "DRAFT"

_PROTOTYPE_FOOTER = (
    "\n\n---\n"
    "Generated by the Claris decision platform from governed state.\n"
    "Governance: {ontology_version} ({governance_basis}, {validation_status}).\n"
    "PROTOTYPE ASSUMPTION -- NOT CLARIS APPROVED. Every governed value behind "
    "this message is an engineering assumption awaiting validation with Claris."
)


@dataclass(frozen=True)
class CommunicationDraft:
    communication_id: str
    subject_id: str
    launch_id: Optional[str]
    from_actor: Optional[str]
    from_role: str
    to_actor: Optional[str]
    to_role: Optional[str]
    channel: str
    communication_type: str
    related_decision_id: Optional[str]
    subject: str
    body: str
    status: str = STATUS_DRAFT

    def as_dict(self) -> dict:
        return {k: getattr(self, k) for k in (
            "communication_id", "subject_id", "launch_id", "from_actor",
            "from_role", "to_actor", "to_role", "channel",
            "communication_type", "related_decision_id", "subject", "body",
            "status")}


def _communication_id(case, coordination, communication_type: str) -> str:
    """Derived from the case and what it is about, so re-drafting the same
    request for the same unchanged case yields the same id rather than a new
    row every time the agent runs."""
    seed = "|".join((
        case.subject_id, communication_type,
        coordination.overall_status,
        str(coordination.waiting_on),
        ",".join(sorted(coordination.missing_evidence)),
        ",".join(sorted(coordination.blocking_decisions)),
    ))
    return "COMM-" + hashlib.sha256(seed.encode("utf-8")).hexdigest()[:12]


def _product_label(case) -> str:
    if case.product and case.product.get("product_name"):
        return case.product["product_name"]
    reference = case.identity_tuple.get("product_reference")
    return reference or case.subject_id


def _identity_line(case) -> str:
    parts = []
    for name, value in case.identity_tuple.items():
        state = case.identity_states.get(name)
        parts.append(f"  {name}: "
                     + (f"{value}" if state == "ESTABLISHED"
                        else f"[{state}]"))
    return "\n".join(parts)


def draft_for(case, coordination, from_role: str = "platform") -> tuple:
    """Zero or more drafts for one analysed case. Sends nothing.

    A cleared case that needs no action produces a NOTE and nothing else: there
    is no one to chase, and generating a chase message anyway is how a
    coordination tool becomes noise people learn to ignore.
    """
    governance = case.governance
    footer = _PROTOTYPE_FOOTER.format(
        ontology_version=governance.get("ontology_version"),
        governance_basis=governance.get("governance_basis"),
        validation_status=governance.get("validation_status"))
    launch_id = (case.launch or {}).get("launch_id")
    product = _product_label(case)
    action = coordination.recommended_next_action

    def build(communication_type, channel, subject, body, decision_id=None):
        return CommunicationDraft(
            communication_id=_communication_id(case, coordination,
                                               communication_type),
            subject_id=case.subject_id,
            launch_id=launch_id,
            from_actor=None,
            from_role=from_role,
            to_actor=coordination.current_owner_actor,
            to_role=coordination.current_owner_role,
            channel=channel,
            communication_type=communication_type,
            related_decision_id=decision_id,
            subject=subject,
            body=body + footer)

    # -- a missing identity input ---------------------------------------
    if action in ("REQUEST_EVIDENCE", "ESTABLISH_DECISION_OWNER"):
        missing = ", ".join(coordination.missing_evidence) or \
            str(coordination.waiting_on)
        blocking_id = (coordination.blocking_decisions[0]
                       if coordination.blocking_decisions else None)
        recipient = (f"the {coordination.current_owner_role} role"
                     if coordination.current_owner_role
                     else "an owner who has not been established")

        body = (
            f"A configuration request for {product} cannot be assessed.\n\n"
            f"Request: {case.subject_id}\n"
            f"{('Launch: ' + launch_id) if launch_id else ''}\n\n"
            f"The governed identity assessment concluded CANNOT_DECIDE because "
            f"the following required identity input is not established:\n\n"
            f"  {missing}\n\n"
            f"Identity as currently observed:\n{_identity_line(case)}\n\n"
            f"No canonical Product, Configuration or ConfigurationVersion has "
            f"been created for this request, and none will be until the input "
            f"is supplied. The platform is not guessing a value.\n\n"
            f"This request is addressed to {recipient}.")

        if action == "ESTABLISH_DECISION_OWNER":
            body += (
                f"\n\nOWNERSHIP IS NOT ESTABLISHED.\n{coordination.owner_basis}"
                f"\n\nSo this cannot be routed with confidence. Establishing who "
                f"owns the {coordination.waiting_on} dimension is itself the "
                f"first action.")
            return (build(TYPE_ESTABLISH_OWNER, CHANNEL_NOTE,
                          f"Owner needed — {product} ({case.subject_id})",
                          body, blocking_id),)

        return (build(TYPE_REQUEST_EVIDENCE, CHANNEL_EMAIL_DRAFT,
                      f"Action required — {product} ({case.subject_id})",
                      body, blocking_id),)

    # -- contradictory governance ---------------------------------------
    if action == "RESOLVE_GOVERNANCE_AMBIGUITY":
        body = (
            f"{product} ({case.subject_id}) carries more than one governed "
            f"decision recorded as current.\n\n"
            f"{coordination.explanation}\n\n"
            f"Decisions involved:\n"
            + "\n".join(f"  {d}" for d in coordination.blocking_decisions)
            + "\n\nThe platform will not choose between them.")
        return (build(TYPE_RESOLVE_AMBIGUITY, CHANNEL_NOTE,
                      f"Governance ambiguity — {product} ({case.subject_id})",
                      body,
                      coordination.blocking_decisions[0]
                      if coordination.blocking_decisions else None),)

    # -- needs a person, cause unknown ----------------------------------
    if action == "HUMAN_REVIEW":
        body = (f"{product} ({case.subject_id}) needs human review.\n\n"
                f"{coordination.explanation}")
        return (build(TYPE_NOTE, CHANNEL_NOTE,
                      f"Review needed — {product} ({case.subject_id})", body),)

    # -- cleared: a note for the record, and nothing to chase ------------
    cleared_id = (coordination.cleared_decisions[0]
                  if coordination.cleared_decisions else None)
    body = (f"{product} ({case.subject_id}) — no action required.\n\n"
            f"{coordination.explanation}")
    return (build(TYPE_NOTE, CHANNEL_NOTE,
                  f"Status — {product} ({case.subject_id})", body, cleared_id),)
